// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TradingAppBE.Infrastructure.EF;

namespace TradingAppBE.Infrastructure.EF.Migrations
{
    [DbContext(typeof(TickersContext))]
    partial class TickersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("TradingAppBE.Infrastructure.EF.DTOs.TickerDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Symbol")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tickers");
                });

            modelBuilder.Entity("TradingAppBE.Infrastructure.EF.DTOs.UserDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TradingAppBE.Infrastructure.EF.DTOs.UserTickerDTO", b =>
                {
                    b.Property<int>("TickerId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("TickerId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserTickers");
                });

            modelBuilder.Entity("TradingAppBE.Infrastructure.EF.DTOs.UserTickerDTO", b =>
                {
                    b.HasOne("TradingAppBE.Infrastructure.EF.DTOs.TickerDTO", "Ticker")
                        .WithMany("UserTickers")
                        .HasForeignKey("TickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradingAppBE.Infrastructure.EF.DTOs.UserDTO", "User")
                        .WithMany("UserTickers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticker");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TradingAppBE.Infrastructure.EF.DTOs.TickerDTO", b =>
                {
                    b.Navigation("UserTickers");
                });

            modelBuilder.Entity("TradingAppBE.Infrastructure.EF.DTOs.UserDTO", b =>
                {
                    b.Navigation("UserTickers");
                });
#pragma warning restore 612, 618
        }
    }
}
